### ISSUE TITLE
What font does the codesandbox use by default?

### ISSUE THREAD

**Issue by suhailga** [ngryman/codesandbox-theme#4]
This theme does not apply the font used by codesandbox. Any idea what font does the codesandbox use?

**Comment by ngryman** [comment]
Here is the stack they use: `Menlo, "Source Code Pro", monospace;`.

**Comment by ngryman** [comment]
I've patched the `README` to mention it: https://github.com/ngryman/codesandbox-theme/blob/master/README.md.
