### ISSUE TITLE
Font isn't updating to match theme

### ISSUE THREAD

**Issue by nats12** [ngryman/codesandbox-theme#6]
Hi, my font isn't updating to look like the screenshot. I've tried adding the three fonts you mentioned in the repo readme - Menlo, "Source Code Pro", monospace - manually under the settings fontFamily property but is still isn't updating. Do we need to change something for the font to update?

**Comment by ngryman** [comment]
Hey, do you have these fonts installed on your machine?

**Comment by nats12** [comment]
Hi @ngryman, yeah I've got all three installed under my macbook's FontBook - Menlo, "Source Code Pro" and monospace. And have added them to my vscode settings file.

**Comment by dedenhabibi** [comment]
Hi @nats12, I got similar issue. So I inspected Codesandbox.io editor and found out `SFMono-Regular` font in the stack. I downloaded (https://fontsfree.net/sf-mono-regular-font-download.html) and installed it, I got this:
![image](https://user-images.githubusercontent.com/4206827/102008517-c587cc80-3d63-11eb-8c78-f0241552a54b.png)

**Comment by dedenhabibi** [comment]
When I use font `Fira Code` (https://github.com/tonsky/FiraCode), I got a very similar appearance with the repo screenshot:
![image](https://user-images.githubusercontent.com/4206827/102009680-aab95600-3d6b-11eb-963b-0b17476c6a91.png)

I believe this is the font actually used by this repo, not the CodeSandBox's. CMIIW

**Comment by ngryman** [comment]
As far as I know, a VSCode theme has nothing to do with font customization. A theme provides colors and font styles (eg. italic) while the typeface is a global setting left at the discretion of the user.

If you take a look at the [theme source](https://github.com/ngryman/codesandbox-theme/blob/master/themes/Codesandbox-color-theme.json) you can see that it only change colors and font styles (eg. italic).

**Comment by dedenhabibi** [comment]
> 
> 
> As far as I know, a VSCode theme has nothing to do with font customization. A theme provides colors and font styles (eg. italic) while the typeface is a global setting left at the discretion of the user.
> 
> If you take a look at the [theme source](https://github.com/ngryman/codesandbox-theme/blob/master/themes/Codesandbox-color-theme.json) you can see that it only change colors and font styles (eg. italic).

Ahh.. I see. Thank you for the explanation. Actually, this theme really does the job 💯 ! Thank you very much 😃

**Comment by ngryman** [comment]
No worries. I'm closing the issue as there's nothing much I can do here.

@nats12 If you still experience an issue when customizing your font, I would suggest [asking the VSCode team for help](https://github.com/microsoft/vscode/issues).

**Comment by nats12** [comment]
Thanks @ngryman , managed to get the font I wanted by adding SFMono-Regular to the list as @dedenhabibi mentioned. Thanks both!
